# Generated by Django 6.1.1 on 2026-09-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default='http://localhost:8000/v1', help_text='例如 http://localhost:8000/v1 或 https://api.openai.com/v1', max_length=300, verbose_name='接口地址（Base URL）')),
                ('api_key', models.CharField(blank=True, default='', help_text='本地部署无需鉴权时可留空', max_length=300, verbose_name='API Key')),
                ('model', models.CharField(default='qwen2.5-7b-instruct', help_text='部署服务中的模型 ID，例如 qwen2.5-7b-instruct、gpt-4o-mini', max_length=200, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature（随机性）')),
                ('max_tokens', models.PositiveIntegerField(blank=True, default=2048, null=True, verbose_name='最大生成 Token 数')),
                ('system_prompt', models.TextField(blank=True, default='你是一个乐于助人的中文 AI 助手。', verbose_name='系统提示词')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API 配置',
                'verbose_name_plural': 'API 配置',
            },
        ),
    ]
